### PR TITLE
rework Custom_Factions, use per-class XEHs instead of iterative logic

### PR DESCRIPTION
**Pull request by freghar**
@milivojm 

Hey, please take a look at this. I re-did basically the whole thing in the end. It started simple and it even worked, but I really, really wanted to make the logic local to the spawned unit, because the XEH was triggering everywhere - with 20 players, you would have 20x gear loading on a single unit (with your original as well as my simple system).

A local check worked perfectly, ... except for the initial load for player units, because `player` is not only REMOTE (not local), it is also `objNull`. One needs to wait and the XEH runs by default in unscheduled environment.

Another issue was with "transfer to server" logic on zeus spawn - the unit was being transferred mid-gear-load, which resulted in a partial gear being loaded, mainly on fireteam/squad leaders about 30% of the time. I plan to solve that by simply delaying the transfer logic by ~30 seconds - it's a good idea regardless as the Zeus might be setting up patrol waypoints and other details that are best left to the client controlling the squad - makes more sense to move it to server once it's been "configured" on the battlefield.

I did various stress testing, holding Ctrl+V, pasting 5-7 squads per second, all loadouts were loaded correctly as long as the transfer-to-server had at least 5 second delay.

You might want to [use the "tree" view](https://github.com/CntoDev/template/tree/e1de164a7def46767e34be46cd4308cf9c6f156f) to see the code as looking at diffs isn't very descriptive. Also please re-read the toplevel (template-wide) README.rst and then the README.rst in the Custom_Factions directory - I moved the "how to activate this feature" description to the global one.

PS: This pull request is just so that you can comment on the changes, please don't merge it via Github.

### CODE REVIEW

**Comment by milivojm** [comment]
Ok, few remarks. 

It's better attaching to specific classes like you did for performance. Why did you use dynamic compile instead of function? Function call is not that expensive and a code would be more readable. 

Of course, without the global array check, typeOf and stuff. 

I would also not recommend using preprocessor command to include a end - user file. They can make a typo and your function will not compile.

**Comment by milivojm** [comment]
I forgot to ask, is cba event handler class name case insensitive?

**Comment by freghar** [comment]
> It's better attaching to specific classes like you did for performance. Why did you use dynamic compile instead of function? Function call is not that expensive and a code would be more readable.

The main reason is inheritance - during execution time (when unit spawns), you no longer have access to the name of the class you added, you can only `typeOf` to get the lowest class. So I work around this by "hard-compiling" the path at the time of XEH addition. `_gen_load` is not a function that runs for each init-ed unit, it's a code generator.

Secondary reason is performance - the `compile` runs only in `preInit`, twice per added class (init/respawn) - during runtime, the code doesn't have to look up classes, concatenate strings, etc., it just gets a full path to the file and executes it. Well, aside from the locality check.

> I would also not recommend using preprocessor command to include a end - user file. They can make a typo and your function will not compile.

It actually doesn't matter - your original approach was also a function that was compiled and if a user made a typo in the arguments, the same error would occur. Whereas with your version, the user would get syntax error in function arguments, with this one, the user gets error when declaring an array - both are syntax errors caught essentially as soon as possible and with Arma's poor error reporting as cryptic as possible. :)

> I forgot to ask, is cba event handler class name case insensitive?

The handler itself is insensitive and the file load as well (at least on Windows). You can specify `b_sOlDieR_f` in `classes.txt`, have a file named `b_soldier_f` and it will still work with `B_Soldier_F`.

**Comment by freghar** [comment]
Also, `compile` is rather fast, about 0.02ms, so that shouldn't be an issue as long as it's not being called 100x per class or something.

**Comment by freghar** [comment]
> I didn't check, but as Windows is (regarding file paths), it should be. On Windows at least.

For the actual file load, I mean - I'll test whether the actual addition/matching is insensitive or not. Good question.

**Comment by milivojm** [comment]
Yes, that is very very clever. I understood the performance gain cause you moved work from every unit spawn to once per class. But I didn't think of Inheritance, great idea!

**Pull request merged**
