### PR TITLE
added functions for holstering off/on

### PR DESCRIPTION
**Pull request by milivojm**
@freghar - I've tried to find a smarter way of doing this but didn't manage. Unfortunately the soldier with weapon reverts to weapons high mode if `disableAI "ANIM"` is not used. The side effect of disabling ANIM is inability of soldier to move. I've seen scripts removing weapons altogether but is that the only way?

### CODE REVIEW

**Comment by freghar** [comment]
Hmm, I want to revisit animations and provide MP-synced functions for playing animation sequences (see https://github.com/CntoDev/template/releases/tag/v0.3), but that wouldn't help here.

Sounds awfully similar to https://github.com/CntoDev/template/blob/7fda63a13d/functions/AI/fn_sitDown.sqf - maybe reuse it with the "weapon on back" action ( https://community.bistudio.com/wiki/Arma_3_Actions#WeaponInHand_.2F_WeaponOnBack ), which should work for pistols as well? .. If the unit has a rifle, make it switch to pistol using https://community.bistudio.com/wiki/Arma_3_Actions#HandGunOn .

If the actions above don't persist for a SAFE unit ([setBehaviour](https://community.bistudio.com/wiki/setBehaviour)) without the `disableAI`, then I'm afraid there's no good alternative and the unit won't be able to move. :( ... This is unlike OPFL, where "weapon on back" was a perfectly valid state for AI (as well as sitting).

**Comment by milivojm** [comment]
Tried it now, unfortunately it doesn't work. WeaponOnBack lowers the weapon, not holster. I've tried it with SAFE and they are still alert. I will keep looking.

**Comment by freghar** [comment]
Yeah, I was playing for a while with https://www.reddit.com/r/arma/comments/2xavmj/arma_3_can_you_holster_your_primary_on_your/coyzq4p and other commands / actions, but it seems vanilla doesn't have any "holster weapon" thing, it can only switch between primary and secondary weapons and if you ie. don't have a primary one, the switch makes you holster the secondary.

It seems to be a custom ACE3 thing. The changes in the pull request also seem to be just switching between primary / secondary weapon, like the actions. :(

There are some potential candidates (https://community.bistudio.com/wiki/ArmA:_Actions#Unsorted_actions_found_in_UI.pbo.2Fconfig.bin), but I wasn't able to make them work either.

**Comment by milivojm** [comment]
It seems this works. It's dark magic but it worked for me. Give it a try.

**Comment by freghar** [comment]
Thanks, I'll try it out tomorrow and (if you want) push it to master. I'd prefer moving it to a single function with true/false argument if you're okay with that (I can do it before push).

**Comment by freghar** [comment]
What about https://github.com/CntoDev/template/commit/c33358a7f74 ?

Can be called as

```
_someunit call A3MT_fnc_holsterPistol;            // holster
[_someunit] call A3MT_fnc_holsterPistol;          // holster
[_someunit, true] call A3MT_fnc_holsterPistol;    // holster
[_someunit, false] call A3MT_fnc_holsterPistol;   // unholster
```

When the unit encounters enemies, it automatically un-holsters. Great find about that -1 by the way.

**Comment by milivojm** [comment]
Looks good, go for it. :)

**Comment by freghar** [comment]
Added as https://github.com/CntoDev/template/commit/c33358a7f74 to master, thanks.

**Pull request closed without merging**
