### PR TITLE
custom factions feature

### PR DESCRIPTION
**Pull request by milivojm**
Custom factions feature (#8) - enables MMs to create new factions
from Arsenal exports.

### CODE REVIEW

**Comment by freghar** [comment]
Push as 1985577b294 , thanks.

I fixed one missing line at EOF in fn_registerGear.sqf and trailing whitespaces introduced by the older commit that was on master, but otherwise - nice work on sorting the git things out!

**Comment by milivojm** [comment]
I still saved your instructions for the rainy days. :)

Filename is called Freghar Ninja GitHub instructions.txt or 'what to do when you screw things up'. Btw. can you post a solution you were talking about last night?

**Comment by freghar** [comment]
Sure, I'd like to do it today/tomorrow, I still have some other changes scheduled for the ares thing + I want to do something IRL as well. :)

**Comment by milivojm** [comment]
Should I delete the branch?

**Comment by freghar** [comment]
No need, it's yours. You can if you want. You should close the issue, though.

**Pull request closed without merging**
